groups:
- name: ProductionAlerts
  rules:
  - alert: HighHttp5xxRate
    expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.05
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: High HTTP 5xx Error Rate in Production
  - alert: PodCrashLooping
    expr: rate(kube_pod_container_status_restarts_total[5m]) > 0
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: Pod is restarting frequently
